import 'package:flutter/material.dart';

import 'models.dart';

final demoUser = AppUser(
  fullName: 'إسماعيل خيربك',
  email: 'ismail@taza041.com',
  phone: '+963 944 123 456',
  loyaltyPoints: 240,
  bio: 'أحب الوجبات السريعة والتجارب الجديدة.',
  city: 'اللاذقية',
  imageLabel: 'Profile Image Placeholder',
);

final products = <Product>[
  const Product(
    id: 'sandwich-1',
    nameAr: 'شاورما دجاج',
    nameEn: 'Chicken Shawarma',
    descriptionAr: 'ساندويش غني بالتتبيلة والصلصة الخاصة.',
    descriptionEn: 'A sandwich packed with signature marinade and sauce.',
    category: ProductCategory.sandwich,
    price: 170,
    rating: 4.7,
    ratingCount: 128,
    isFeatured: true,
    placeholderLabel: 'Sandwich Product Image 1',
  ),
  const Product(
    id: 'sandwich-2',
    nameAr: 'زنجر سبايسي',
    nameEn: 'Spicy Zinger',
    descriptionAr: 'مقرمش وحار مع خبز طري وخضار طازجة.',
    descriptionEn: 'Crunchy spicy fillet with soft bread and fresh greens.',
    category: ProductCategory.sandwich,
    price: 185,
    rating: 4.5,
    ratingCount: 96,
    placeholderLabel: 'Sandwich Product Image 2',
  ),
  const Product(
    id: 'meal-1',
    nameAr: 'وجبة كريسبي',
    nameEn: 'Crispy Meal',
    descriptionAr: 'وجبة كاملة مع بطاطا ومشروب ضمن تقديم عصري.',
    descriptionEn:
        'A complete meal with fries and a drink in a modern presentation.',
    category: ProductCategory.meal,
    price: 280,
    rating: 4.8,
    ratingCount: 173,
    isFeatured: true,
    placeholderLabel: 'Meal Product Image 1',
  ),
  const Product(
    id: 'meal-2',
    nameAr: 'بيتزا مارجريتا',
    nameEn: 'Margherita Pizza',
    descriptionAr: 'بيتزا بطعم كلاسيكي ومكونات متوازنة.',
    descriptionEn: 'Classic pizza with balanced ingredients and flavour.',
    category: ProductCategory.meal,
    price: 260,
    rating: 4.6,
    ratingCount: 142,
    isFeatured: true,
    placeholderLabel: 'Meal Product Image 2',
  ),
  const Product(
    id: 'meal-3',
    nameAr: 'برغر كلاسيكي',
    nameEn: 'Classic Burger',
    descriptionAr: 'برغر سميك مع صوص المطعم الخاص.',
    descriptionEn: 'A thick burger with the house signature sauce.',
    category: ProductCategory.meal,
    price: 190,
    rating: 4.4,
    ratingCount: 88,
    isFeatured: true,
    placeholderLabel: 'Meal Product Image 3',
  ),
  const Product(
    id: 'drink-1',
    nameAr: 'عصير برتقال',
    nameEn: 'Orange Fresh',
    descriptionAr: 'مشروب بارد ومنعش مناسب لكل الوجبات.',
    descriptionEn: 'A refreshing cold drink that pairs well with every meal.',
    category: ProductCategory.drink,
    price: 90,
    rating: 4.3,
    ratingCount: 64,
    isFeatured: true,
    placeholderLabel: 'Drink Product Image 1',
  ),
  const Product(
    id: 'drink-2',
    nameAr: 'مشروب غازي',
    nameEn: 'Soft Drink',
    descriptionAr: 'خيارات متعددة من المشروبات الغازية الباردة.',
    descriptionEn: 'Multiple chilled soft drink options.',
    category: ProductCategory.drink,
    price: 70,
    rating: 4.1,
    ratingCount: 52,
    placeholderLabel: 'Drink Product Image 2',
  ),
  const Product(
    id: 'offer-1',
    nameAr: 'عرض البيتزا اليومي',
    nameEn: 'Daily Pizza Offer',
    descriptionAr: 'بيتزا + مشروب بسعر مخفض لفترة محدودة.',
    descriptionEn: 'Pizza + drink at a discounted price for a limited time.',
    category: ProductCategory.offer,
    price: 250,
    oldPrice: 330,
    rating: 4.9,
    ratingCount: 201,
    isFeatured: true,
    placeholderLabel: 'Offer Product Image 1',
  ),
  const Product(
    id: 'offer-2',
    nameAr: 'كومبو الطلاب',
    nameEn: 'Student Combo',
    descriptionAr: 'وجبة سريعة مناسبة لطلب يومي بقيمة ممتازة.',
    descriptionEn: 'A smart daily combo with great value for students.',
    category: ProductCategory.offer,
    price: 140,
    oldPrice: 180,
    rating: 4.5,
    ratingCount: 119,
    placeholderLabel: 'Offer Product Image 2',
  ),
];

final drivers = <DriverProfile>[
  const DriverProfile(
    id: 'driver-1',
    nameAr: 'ليث مرعي',
    nameEn: 'Laith Marai',
    descriptionAr: 'سائق سريع وملتزم داخل المدينة.',
    descriptionEn: 'Fast and reliable driver inside the city.',
    rating: 4.8,
    priceHintAr: 'تسعير ذكي حسب المسافة',
    priceHintEn: 'Smart pricing by distance',
    placeholderLabel: 'Driver Image 1',
  ),
  const DriverProfile(
    id: 'driver-2',
    nameAr: 'يوسف أسعد',
    nameEn: 'Yousef Asaad',
    descriptionAr: 'خبرة ممتازة ومسار واضح للتوصيل.',
    descriptionEn: 'Excellent routing experience and smooth delivery.',
    rating: 4.7,
    priceHintAr: 'تقييم عالٍ من الزبائن',
    priceHintEn: 'Highly rated by customers',
    placeholderLabel: 'Driver Image 2',
  ),
  const DriverProfile(
    id: 'driver-3',
    nameAr: 'نضال طالب',
    nameEn: 'Nidal Taleb',
    descriptionAr: 'خدمة راقية وسرعة استجابة عالية.',
    descriptionEn: 'Premium service with a fast response.',
    rating: 4.6,
    priceHintAr: 'تغطية ممتازة للمناطق القريبة',
    priceHintEn: 'Excellent coverage for nearby areas',
    placeholderLabel: 'Driver Image 3',
  ),
];

final demoNotifications = <NotificationItem>[
  NotificationItem(
    id: 'n1',
    titleAr: 'مرحبًا بك في TAZA 041 🎉',
    titleEn: 'Welcome to TAZA 041 🎉',
    messageAr: 'نحن سعداء بانضمامك إلينا ونتمنى لك تجربة رائعة معنا.',
    messageEn:
        'We are happy to have you here and hope you enjoy the experience.',
    timeLabelAr: 'الآن',
    timeLabelEn: 'Now',
    icon: Icons.celebration,
  ),
  NotificationItem(
    id: 'n2',
    titleAr: 'ابدأ أول طلب لك 🍽️',
    titleEn: 'Start your first order 🍽️',
    messageAr: 'تصفح المنيو واختر وجبتك المفضلة بسهولة.',
    messageEn: 'Browse the menu and pick your favourite meal with ease.',
    timeLabelAr: 'اليوم',
    timeLabelEn: 'Today',
    icon: Icons.restaurant_menu,
    isRead: true,
  ),
  NotificationItem(
    id: 'n3',
    titleAr: 'اكتشف العروض اليومية 🔥',
    titleEn: 'Discover daily offers 🔥',
    messageAr: 'لا تفوت أفضل العروض المتاحة اليوم.',
    messageEn: 'Do not miss the best offers available today.',
    timeLabelAr: 'منذ دقيقة',
    timeLabelEn: '1 min ago',
    icon: Icons.local_fire_department,
  ),
];

final initialOrders = <OrderRecord>[
  OrderRecord(
    id: 'ORD-041-1',
    type: OrderType.ordinary,
    status: OrderStatus.pending,
    items: [
      CartItem(product: products[0], quantity: 1),
      CartItem(product: products[6], quantity: 1)
    ],
    createdAtLabelAr: 'اليوم - 10:15 ص',
    createdAtLabelEn: 'Today - 10:15 AM',
    paymentMethod: PaymentMethod.shamCash,
    baseTotal: 240,
    finalTotal: 240,
    loyaltyAwarded: 24,
  ),
  OrderRecord(
    id: 'ORD-041-2',
    type: OrderType.delivery,
    status: OrderStatus.inProgress,
    items: [
      CartItem(product: products[2], quantity: 1),
      CartItem(product: products[5], quantity: 2)
    ],
    createdAtLabelAr: 'الأمس - 7:40 م',
    createdAtLabelEn: 'Yesterday - 7:40 PM',
    paymentMethod: PaymentMethod.syriatelCash,
    baseTotal: 460,
    finalTotal: 520,
    deliveryAddress: 'دوار الزراعة - اللاذقية',
    deliveryDistanceMeters: 1200,
    deliveryCost: 60,
    driver: drivers[0],
    loyaltyAwarded: 52,
  ),
  OrderRecord(
    id: 'ORD-041-3',
    type: OrderType.reservation,
    status: OrderStatus.cancelled,
    items: [CartItem(product: products[1], quantity: 2)],
    createdAtLabelAr: 'قبل يومين',
    createdAtLabelEn: '2 days ago',
    paymentMethod: PaymentMethod.loyaltyPoints,
    baseTotal: 370,
    finalTotal: 500,
    tableNumber: 7,
    isVipTable: true,
    seatsCount: 4,
    reservationTimeLabel: '08:30 PM',
    loyaltyAwarded: 0,
  ),
];

const restaurantAddressAr = 'اللاذقية - شارع الزراعة - مقابل السكن الجامعي';
const restaurantAddressEn =
    'Latakia - Agriculture Street - opposite the university dorms';
const restaurantHoursAr = '10:00 صباحاً - 12:00 منتصف الليل';
const restaurantHoursEn = '10:00 AM - 12:00 AM';

final aiKnownKeywords = <String, String>{
  'بيتزا': 'meal-2',
  'pizza': 'meal-2',
  'برغر': 'meal-3',
  'burger': 'meal-3',
  'شاورما': 'sandwich-1',
  'shawarma': 'sandwich-1',
  'كريسبي': 'meal-1',
  'crispy': 'meal-1',
  'مشروب': 'drink-1',
  'drink': 'drink-1',
};

final demoLocations = <({String ar, String en, int meters})>[
  (ar: 'مقابل السكن الجامعي', en: 'Opposite university dorms', meters: 600),
  (ar: 'دوار الزراعة', en: 'Agriculture roundabout', meters: 1200),
  (ar: 'حي المشروع السابع', en: 'Project 7 district', meters: 2300),
];

final reservationTables = <({int number, bool isReserved, bool isVip})>[
  (number: 1, isReserved: false, isVip: false),
  (number: 2, isReserved: true, isVip: false),
  (number: 3, isReserved: false, isVip: true),
  (number: 4, isReserved: false, isVip: false),
  (number: 5, isReserved: true, isVip: false),
  (number: 6, isReserved: false, isVip: true),
  (number: 7, isReserved: false, isVip: false),
  (number: 8, isReserved: false, isVip: false),
];
